# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies.
resolver: lts-18.23

# User packages to be built.
packages:
- lighthouse-client
- lighthouse-demo

extra-deps:
- msgpack-1.0.1.0
