name:                lighthouse-demo
version:             0.2.0.0
github:              "ProjectLighthouseCAU/project-lighthouse-haskell"
license:             BSD3
author:              "Project Lighthouse team"
copyright:           "2020 fwcd"

extra-source-files:
- README.md

synopsis:            Demo of the Lighthouse API
category:            Application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ProjectLighthouseCAU/lighthouse-haskell#readme>

dependencies:
- base         >= 4.17  && < 5
- text         >= 2.1   && < 3
- mtl          >= 2.3   && < 3
- transformers >= 0.6   && < 1
- random       >= 1.2.1 && < 2
- JuicyPixels  >= 3.3   && < 4

executables:
  lighthouse-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - lighthouse-client
