name:                lighthouse-demo
version:             0.1.0.0
github:              "fwcd/project-lighthouse-haskell"
license:             BSD3
author:              "fwcd"
copyright:           "2020 fwcd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fwcd/project-lighthouse-haskell#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  lighthouse-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lighthouse-api

# tests:
#   lighthouse-demo-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lighthouse-demo
