name:                lighthouse-client
version:             0.1.0.0
github:              "ProjectLighthouseCAU/project-lighthouse-haskell"
license:             BSD3
author:              "Project Lighthouse team"
copyright:           "2020 fwcd"

extra-source-files:
- README.md

synopsis:            Project Lighthouse client SDK
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ProjectLighthouseCAU/project-lighthouse-haskell#readme>

dependencies:
- base         >= 4.17  && < 5
- bytestring   >= 0.11  && < 1
- text         >= 2.1   && < 3
- random       >= 1.2.1 && < 2
- mtl          >= 2.3   && < 3
- transformers >= 0.6   && < 1
- vector       >= 0.13  && < 1
- msgpack      >= 1.0   && < 2
- network      >= 3.1   && < 4
- websockets   >= 0.12  && < 1
- wuss         >= 2.0   && < 3

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  lighthouse-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - lighthouse-client
