name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Haskell and Stack
      uses: actions/setup-haskell@v1
      with:
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack build
