name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Pages
      uses: actions/configure-pages@v3
    - name: Set up Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-version: 'latest'
    - name: Generate Docs
      run: |
        stack haddock --no-haddock-deps --fast
        dist_dir=$(stack path --dist-dir)
        pkg_name=lighthouse-client
        cp -r $pkg_name/$dist_dir/doc/html/$pkg_name doc
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v2
